#开发配置
spring:
  profiles:
    active: dev

  datasource:
    hive:
      url: jdbc:hive2://101.201.237.57:10000/stage
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      type: com.alibaba.druid.pool.DruidDataSource
      user: qjy365itrigger
      password:
      
    mysql:
      url: jdbc:mysql://101.201.237.57:3306/bigScreen?characterEncoding=utf-8&useSSL=true
      username: hive
      password: hive
      driver-class-name: com.mysql.cj.jdbc.Driver
      #type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  typeAliasesPackage: com.itrigger.entity
  mapper-locations: classpath:mapper/*.xml
